package goMoku.Controller;

import goMoku.Model.GameBoard;
import goMoku.View.IGoMokuView;
import java.awt.Point;
import java.util.Random;

/**
 * ComputerPlayer implementation to the Player abstract class
 * Currently the computer doesn't use any game-play logic. 
 * It just generates random moves. 
 */
public class ComputerPlayer extends Player {
	
	public ComputerPlayer (GameBoard board, IGoMokuView view, String name, char mark) {
		super(board, view, name, mark);
	}
	
	/**
	 * @return Move coordinates generated by the computer  
	 */
	public Point makeMove() {
		
		int board_size = m_board.getSize();
		
		/* will be used for guessing the next move */
		Random random_generator = new Random();	
		int x,y;
		
		do {
			/* 
			 * nextInt returns number in range 0 to (board_size-1)
			 * we need to add one to both coordinates to convert it to the right range
			 */
			x = random_generator.nextInt(board_size) + 1;
			y = random_generator.nextInt(board_size) + 1;
		
		} while (m_board.hasPawn(x, y));
		
		
		return new Point(x,y);
	}
	
}
